from termcolor import colored
import game_race
import game_class
import game_background
import player


def line():
    print(colored('{txt:*^119}'.format(txt='*'), 'blue'))


result_race = game_race.input_race()
result_class = game_class.input_class()
result_background = game_background.input_background()

# personality_traits = ''  # черты характера
# ideals = ''  # идеалы
# bonds = ''  # привязанности
# flaws = ''  # слабости


print(colored('Итого:', color='cyan'))

line()
print(colored('имя игрока', color='cyan'), '=', colored(player.name_player, color='yellow'))
line()
print(colored('имя персонажа', color='cyan'), '=', colored(player.name, color='yellow'))
print(colored('пол персонажа', color='cyan'), '=', colored(player.game_gender, color='yellow'))
print(colored('возраст персонажа', color='cyan'), '=', colored(player.age, color='yellow'))
print(colored('рост персонажа', color='cyan'), '=', colored(player.height, color='yellow'))
print(colored('вес персонажа', color='cyan'), '=', colored(player.weight, color='yellow'))
line()
print(colored('раса', color='cyan'), '=', colored(player.race, color='yellow'))
print(colored('класс', color='cyan'), '=', colored(player.game_class, color='yellow'))
print(colored('предыстория', color='cyan'), '=', colored(player.background, color='yellow'))
print(colored('мировоззрение', color='cyan'), '=', colored(player.alignment, color='yellow'))
line()
print(colored('черты характера', color='cyan'), '=', colored(player.personality_traits, color='yellow'))
print(colored('идеалы', color='cyan'), '=', colored(player.ideals, color='yellow'))
print(colored('привязанности', color='cyan'), '=', colored(player.bonds, color='yellow'))
print(colored('слабости', color='cyan'), '=', colored(player.flaws, color='yellow'))
line()
print(colored('уровень', color='cyan'), '=', colored(player.level, color='yellow'))
print(colored('опыт', color='cyan'), '=', colored(player.experience_point, color='yellow'))
line()
print(colored('сила', color='cyan'), '=', colored(player.strength, color='yellow'))
print(colored('ловкость', color='cyan'), '=', colored(player.dexterity, color='yellow'))
print(colored('телосложение', color='cyan'), '=', colored(player.constitution, color='yellow'))
print(colored('интеллект', color='cyan'), '=', colored(player.intelligence, color='yellow'))
print(colored('мудрость', color='cyan'), '=', colored(player.wisdom, color='yellow'))
print(colored('харизма', color='cyan'), '=', colored(player.charisma, color='yellow'))
line()
print(colored('бонус мастерства', color='cyan'), '=', colored(player.proficiency_bonus, color='yellow'))
line()
print(colored('модификатор сила', color='cyan'), '=', colored(player.mod_strength, color='yellow'))
print(colored('модификатор ловкость', color='cyan'), '=', colored(player.mod_dexterity, color='yellow'))
print(colored('модификатор телосложение', color='cyan'), '=', colored(player.mod_constitution, color='yellow'))
print(colored('модификатор интеллект', color='cyan'), '=', colored(player.mod_intelligence, color='yellow'))
print(colored('модификатор мудрость', color='cyan'), '=', colored(player.mod_wisdom, color='yellow'))
print(colored('модификатор харизма', color='cyan'), '=', colored(player.mod_charisma, color='yellow'))
line()
print(colored('спас бросок сила', color='cyan'), '=', colored(player.saving_throws_strength, color='yellow'))
print(colored('спас бросок ловкость', color='cyan'), '=', colored(player.saving_throws_dexterity, color='yellow'))
print(colored('спас бросок телосложение', color='cyan'), '=', colored(player.saving_throws_constitution, color='yellow'))
print(colored('спас бросок интеллект', color='cyan'), '=', colored(player.saving_throws_intelligence, color='yellow'))
print(colored('спас бросок мудрость', color='cyan'), '=', colored(player.saving_throws_wisdom, color='yellow'))
print(colored('спас бросок харизма', color='cyan'), '=', colored(player.saving_throws_charisma, color='yellow'))
line()
print(colored('знание спас броска сила', color='cyan'), '=', colored(player.check_saving_throws_strength, color='yellow'))
print(colored('знание спас броска ловкость', color='cyan'), '=', colored(player.check_saving_throws_dexterity, color='yellow'))
print(colored('знание спас броска телосложение', color='cyan'), '=', colored(player.check_saving_throws_constitution, color='yellow'))
print(colored('знание спас броска интеллект', color='cyan'), '=', colored(player.check_saving_throws_intelligence, color='yellow'))
print(colored('знание спас броска мудрость', color='cyan'), '=', colored(player.check_saving_throws_wisdom, color='yellow'))
print(colored('знание спас броска харизма', color='cyan'), '=', colored(player.check_saving_throws_charisma, color='yellow'))
line()
print(colored('акробатика', color='cyan'), '=', colored(player.acrobatics, color='yellow'))
print(colored('анализ', color='cyan'), '=', colored(player.perception, color='yellow'))
print(colored('атлетика', color='cyan'), '=', colored(player.athletics, color='yellow'))
print(colored('внимательность', color='cyan'), '=', colored(player.investigation, color='yellow'))
print(colored('выживание', color='cyan'), '=', colored(player.survival, color='yellow'))
print(colored('выступление', color='cyan'), '=', colored(player.performance, color='yellow'))
print(colored('запугивание', color='cyan'), '=', colored(player.intimidation, color='yellow'))
print(colored('история', color='cyan'), '=', colored(player.history, color='yellow'))
print(colored('ловкость рук', color='cyan'), '=', colored(player.sleight_of_hand, color='yellow'))
print(colored('магия', color='cyan'), '=', colored(player.arcana, color='yellow'))
print(colored('медицина', color='cyan'), '=', colored(player.medicine, color='yellow'))
print(colored('обман', color='cyan'), '=', colored(player.deception, color='yellow'))
print(colored('природа', color='cyan'), '=', colored(player.nature, color='yellow'))
print(colored('проницательность', color='cyan'), '=', colored(player.insight, color='yellow'))
print(colored('религия', color='cyan'), '=', colored(player.religion, color='yellow'))
print(colored('скрытность', color='cyan'), '=', colored(player.stealth, color='yellow'))
print(colored('убеждение', color='cyan'), '=', colored(player.persuasion, color='yellow'))
print(colored('уход за животными', color='cyan'), '=', colored(player.animal_handling, color='yellow'))
line()
print(colored('пассивная мудрость (внимательность)', color='cyan'), '=', colored(player.passive_wisdom, color='yellow'))
line()
print(colored('КД (класс доспеха)', color='cyan'), '=', colored(player.armor_class, color='yellow'))
print(colored('инициатива', color='cyan'), '=', colored(player.initiative, color='yellow'))
print(colored('скорость', color='cyan'), '=', colored(player.speed, color='yellow'))
line()
print(colored('максимальное кол-во очков жизни', color='cyan'), '=', colored(player.hit_point_maximum, color='yellow'))
print(colored('кубик жизни', color='cyan'), '=', colored(player.hit_dise, color='yellow'))
line()
print(colored('темное зрение', color='cyan'), '=', colored(player.dark_vision, color='yellow'))
print(colored('языки', color='cyan'), '=', colored(player.language, color='yellow'))
line()
print(colored('другие умения', color='cyan'), '=', colored(player.other, color='yellow'))
print(colored('навыки', color='cyan'), '=', colored(player.skills, color='yellow'))
print(colored('снаряжение', color='cyan'), '=', colored(player.equipment, color='yellow'))
line()
